/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package horizonlogistic;

import java.awt.Component;
import java.sql.*;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ButtonGroup;


/**
 *
 * @author RAYHAN EGAR
 */
public class DashboardPayment extends javax.swing.JFrame {
     private String connectionUrl = "jdbc:sqlserver://DESKTOP-OOI580Q:1433;"
                + "database=Horizon_Logistic;"
                + "user=sa;"
                + "password=123;"
                + "encrypt=false;"
                + "trustServerCertificate=false;"
                + "loginTimeout=30;";
    
    private ResultSet resultSet = null;
    private Connection connection;
    private Statement statement;
    private PreparedStatement preparedStatement;
    private Map<String, JTextField> jtfMap;
    private Map<String, JLabel> jlMap;
    private String section;
    private String email_cust;
    private int fieldCount;
    
    /**
     * Creates new form DashboardAdmin
     */
    public DashboardPayment() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpSidebar = new javax.swing.JPanel();
        jlSidebarTitle = new javax.swing.JLabel();
        jbtnBackMenu = new javax.swing.JButton();
        jlSidebarTitle1 = new javax.swing.JLabel();
        jlSidebarTitle3 = new javax.swing.JLabel();
        jlSidebarTitle4 = new javax.swing.JLabel();
        jlSidebarTitle5 = new javax.swing.JLabel();
        jpContent = new javax.swing.JPanel();
        jpContent2 = new javax.swing.JPanel();
        jlSectionTitle = new javax.swing.JLabel();
        jspTable = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jlSectionDetail = new javax.swing.JLabel();
        jBtnRefresh = new javax.swing.JButton();
        jspDetail = new javax.swing.JScrollPane();
        jpDetail = new javax.swing.JPanel();
        jtfField1 = new javax.swing.JTextField();
        jlField1 = new javax.swing.JLabel();
        jlField2 = new javax.swing.JLabel();
        jtfField2 = new javax.swing.JTextField();
        jtfField3 = new javax.swing.JTextField();
        jlField3 = new javax.swing.JLabel();
        jlField4 = new javax.swing.JLabel();
        jlField5 = new javax.swing.JLabel();
        jtfField4 = new javax.swing.JTextField();
        jtfField5 = new javax.swing.JTextField();
        jtfField6 = new javax.swing.JTextField();
        jtfField7 = new javax.swing.JTextField();
        jtfField8 = new javax.swing.JTextField();
        jtfField9 = new javax.swing.JTextField();
        jtfField10 = new javax.swing.JTextField();
        jtfField11 = new javax.swing.JTextField();
        jtfField12 = new javax.swing.JTextField();
        jtfField13 = new javax.swing.JTextField();
        jlField6 = new javax.swing.JLabel();
        jlField7 = new javax.swing.JLabel();
        jlField8 = new javax.swing.JLabel();
        jlField9 = new javax.swing.JLabel();
        jlField10 = new javax.swing.JLabel();
        jlField11 = new javax.swing.JLabel();
        jlField12 = new javax.swing.JLabel();
        jlField13 = new javax.swing.JLabel();
        jBtnRegister = new javax.swing.JButton();
        jlSectionTitle1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Horizon Logistic");
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);

        jpSidebar.setBackground(new java.awt.Color(255, 255, 255));
        jpSidebar.setFocusable(false);
        jpSidebar.setPreferredSize(new java.awt.Dimension(250, 600));

        jlSidebarTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlSidebarTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSidebarTitle.setText("DASHBOARD");
        jlSidebarTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlSidebarTitle.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jbtnBackMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnBackMenu.setText("Back to Menu");
        jbtnBackMenu.setPreferredSize(new java.awt.Dimension(150, 30));
        jbtnBackMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBackMenuActionPerformed(evt);
            }
        });

        jlSidebarTitle1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlSidebarTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSidebarTitle1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/horizonlogistic/Horizon Logistic Logo Resize.png"))); // NOI18N
        jlSidebarTitle1.setText("Horizon Logistic");
        jlSidebarTitle1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlSidebarTitle1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jlSidebarTitle3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlSidebarTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSidebarTitle3.setText("==============");
        jlSidebarTitle3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlSidebarTitle3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jlSidebarTitle4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlSidebarTitle4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSidebarTitle4.setText("==============");
        jlSidebarTitle4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlSidebarTitle4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jlSidebarTitle5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlSidebarTitle5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSidebarTitle5.setText("PAYMENT");
        jlSidebarTitle5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlSidebarTitle5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jpSidebarLayout = new javax.swing.GroupLayout(jpSidebar);
        jpSidebar.setLayout(jpSidebarLayout);
        jpSidebarLayout.setHorizontalGroup(
            jpSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSidebarLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jbtnBackMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlSidebarTitle3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlSidebarTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlSidebarTitle4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlSidebarTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jpSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpSidebarLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jlSidebarTitle5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jpSidebarLayout.setVerticalGroup(
            jpSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSidebarLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jlSidebarTitle1)
                .addGap(18, 18, 18)
                .addComponent(jlSidebarTitle4)
                .addGap(44, 44, 44)
                .addComponent(jlSidebarTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlSidebarTitle3)
                .addGap(66, 66, 66)
                .addComponent(jbtnBackMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpSidebarLayout.createSequentialGroup()
                    .addGap(263, 263, 263)
                    .addComponent(jlSidebarTitle5)
                    .addContainerGap(392, Short.MAX_VALUE)))
        );

        jpContent.setBackground(new java.awt.Color(255, 255, 255));
        jpContent.setPreferredSize(new java.awt.Dimension(600, 100));

        jpContent2.setBackground(new java.awt.Color(255, 255, 255));
        jpContent2.setPreferredSize(new java.awt.Dimension(600, 100));

        jlSectionTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlSectionTitle.setText("Shipment Payment");
        jlSectionTitle.setPreferredSize(new java.awt.Dimension(320, 32));

        jspTable.setBackground(new java.awt.Color(255, 255, 255));
        jspTable.setPreferredSize(new java.awt.Dimension(690, 240));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspTable.setViewportView(jTable);

        jlSectionDetail.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlSectionDetail.setText("Payment Detail");
        jlSectionDetail.setPreferredSize(new java.awt.Dimension(100, 32));

        jBtnRefresh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnRefresh.setText("Refresh");
        jBtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRefreshActionPerformed(evt);
            }
        });

        jpDetail.setBackground(new java.awt.Color(255, 255, 255));
        jpDetail.setPreferredSize(new java.awt.Dimension(450, 500));

        jtfField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfField1ActionPerformed(evt);
            }
        });

        jlField1.setText("field-1");

        jlField2.setText("field-2");

        jlField3.setText("field-3");

        jlField4.setText("field-4");

        jlField5.setText("field-5");

        jlField6.setText("field-6");

        jlField7.setText("field-7");

        jlField8.setText("field-8");

        jlField9.setText("field-9");

        jlField10.setText("field-10");

        jlField11.setText("field-11");

        jlField12.setText("field-12");

        jlField13.setText("field-13");

        javax.swing.GroupLayout jpDetailLayout = new javax.swing.GroupLayout(jpDetail);
        jpDetail.setLayout(jpDetailLayout);
        jpDetailLayout.setHorizontalGroup(
            jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetailLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDetailLayout.createSequentialGroup()
                        .addComponent(jlField1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDetailLayout.createSequentialGroup()
                        .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlField2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlField3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlField4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlField5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlField6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlField7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlField8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlField9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlField10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlField11, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlField12, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlField13, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfField2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfField3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfField4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfField5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfField6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfField7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfField8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfField9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfField10, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfField11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfField12, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfField13, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jpDetailLayout.setVerticalGroup(
            jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetailLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlField2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlField3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlField4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlField5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlField6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlField7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlField8)
                    .addComponent(jtfField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlField9)
                    .addComponent(jtfField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlField10)
                    .addComponent(jtfField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlField11)
                    .addComponent(jtfField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlField12)
                    .addComponent(jtfField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlField13)
                    .addComponent(jtfField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jspDetail.setViewportView(jpDetail);

        jBtnRegister.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jBtnRegister.setText("Pay Now");
        jBtnRegister.setEnabled(false);
        jBtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegisterActionPerformed(evt);
            }
        });

        jlSectionTitle1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jlSectionTitle1.setText("Make payment of the shipment you made!");
        jlSectionTitle1.setPreferredSize(new java.awt.Dimension(320, 32));

        javax.swing.GroupLayout jpContent2Layout = new javax.swing.GroupLayout(jpContent2);
        jpContent2.setLayout(jpContent2Layout);
        jpContent2Layout.setHorizontalGroup(
            jpContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContent2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlSectionTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpContent2Layout.createSequentialGroup()
                        .addGroup(jpContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpContent2Layout.createSequentialGroup()
                                .addComponent(jlSectionTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(294, 294, 294)
                                .addComponent(jBtnRefresh))
                            .addGroup(jpContent2Layout.createSequentialGroup()
                                .addGroup(jpContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jspDetail)
                                    .addComponent(jlSectionDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jspTable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpContent2Layout.setVerticalGroup(
            jpContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContent2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jlSectionTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlSectionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jspTable, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpContent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpContent2Layout.createSequentialGroup()
                        .addComponent(jlSectionDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jspDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtnRegister))
                .addGap(112, 112, 112))
        );

        javax.swing.GroupLayout jpContentLayout = new javax.swing.GroupLayout(jpContent);
        jpContent.setLayout(jpContentLayout);
        jpContentLayout.setHorizontalGroup(
            jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpContent2, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpContentLayout.setVerticalGroup(
            jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpContent2, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpContent, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void jbtnBackMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBackMenuActionPerformed
        CustomerMenu CM = new CustomerMenu(email_cust);
        CM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnBackMenuActionPerformed

    private void jBtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegisterActionPerformed
        // TODO add your handling code here:
        try {
            if (checkEmpty()) {
                JOptionPane.showMessageDialog(this,
                    "Please fill every active field.",
                    "Empty Field!",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            String preparedString = "INSERT INTO " + section + " VALUES (";
            for (int i = 0; i < fieldCount; i++) {

                if (i == fieldCount-1){
                    preparedString += "?)";
                }
                else {
                    preparedString += "?, ";
                }
            }

            PreparedStatement insertStatement = connection.prepareStatement(preparedString);
            switch (section) {
                case "customer":
                insertStatement.setString(1, jtfField1.getText());
                insertStatement.setString(2, jtfField2.getText());
                insertStatement.setString(3, jtfField3.getText());
                insertStatement.setInt(4, Integer.parseInt(jtfField4.getText()));
                insertStatement.setString(5, jtfField5.getText());
                insertStatement.setString(6, jtfField6.getText());
                insertStatement.setString(7, jtfField7.getText());
                insertStatement.setString(8, jtfField8.getText());
                insertStatement.setString(9, jtfField9.getText());
                insertStatement.setString(10, jtfField10.getText());
                break;
                case "shipment":
                insertStatement.setString(1, jtfField1.getText());
                insertStatement.setString(2, jtfField2.getText());
                insertStatement.setString(3, jtfField3.getText());
                insertStatement.setString(4, jtfField4.getText());
                insertStatement.setString(5, jtfField5.getText());
                insertStatement.setFloat(6, Float.parseFloat(jtfField6.getText()));
                insertStatement.setString(7, jtfField7.getText());
                insertStatement.setFloat(8, Float.parseFloat(jtfField8.getText()));
                insertStatement.setString(9, jtfField9.getText());
                insertStatement.setFloat(10, Float.parseFloat(jtfField10.getText()));
                insertStatement.setString(11, jtfField11.getText());
                insertStatement.setString(12, jtfField12.getText());
                insertStatement.setString(13, jtfField13.getText());
                break;
                case "employee":
                insertStatement.setString(1, jtfField1.getText());
                insertStatement.setString(2, jtfField2.getText());
                insertStatement.setString(3, jtfField3.getText());
                insertStatement.setString(4, jtfField4.getText());
                insertStatement.setString(5, jtfField5.getText());
                insertStatement.setString(6, jtfField6.getText());
                insertStatement.setString(7, jtfField7.getText());
                insertStatement.setString(8, jtfField8.getText());
                insertStatement.setString(9, jtfField9.getText());
                insertStatement.setFloat(10, Float.parseFloat(jtfField10.getText()));
                insertStatement.setString(11, jtfField11.getText());
                insertStatement.setString(12, jtfField12.getText());
                break;
                case "clearance":
                insertStatement.setString(1, jtfField1.getText());
                insertStatement.setFloat(2, Float.parseFloat(jtfField2.getText()));
                insertStatement.setString(3, jtfField3.getText());
                insertStatement.setString(4, jtfField4.getText());
                break;
                case "kendaraan":
                insertStatement.setString(1, jtfField1.getText());
                insertStatement.setString(2, jtfField2.getText());
                insertStatement.setString(3, jtfField3.getText());
                insertStatement.setString(4, jtfField4.getText());
                insertStatement.setString(5, jtfField5.getText());
                insertStatement.setInt(6, Integer.parseInt(jtfField6.getText()));
                break;
                case "delivery_leg":
                insertStatement.setString(1, jtfField1.getText());
                insertStatement.setString(2, jtfField2.getText());
                insertStatement.setString(3, jtfField3.getText());
                insertStatement.setString(4, jtfField4.getText());
                insertStatement.setString(5, jtfField1.getText());
                break;
                case "droppoint":
                insertStatement.setString(1, jtfField1.getText());
                insertStatement.setString(2, jtfField2.getText());
                insertStatement.setString(3, jtfField3.getText());
                insertStatement.setString(4, jtfField4.getText());
                insertStatement.setString(5, jtfField5.getText());
                insertStatement.setString(6, jtfField6.getText());
                insertStatement.setString(7, jtfField7.getText());
                break;
                case "payment":
                insertStatement.setString(1, jtfField1.getText());
                insertStatement.setFloat(2, Float.parseFloat(jtfField2.getText()));
                insertStatement.setFloat(3, Float.parseFloat(jtfField3.getText()));
                insertStatement.setFloat(4, Float.parseFloat(jtfField4.getText()));
                insertStatement.setString(5, jtfField5.getText());
                break;
                case "operates":
                insertStatement.setString(1, jtfField1.getText());
                insertStatement.setString(2, jtfField2.getText());
                break;
            }

            int confirmation = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to register new entry?",
                "Register Confirmation",
                JOptionPane.YES_NO_OPTION
            );

            if(confirmation == JOptionPane.YES_OPTION){
                insertStatement.execute();
                System.out.println("Successfully register new entry to "+ section + " ID no: " + jtfField1.getText());
                JOptionPane.showMessageDialog(this, "Successfully registered.", "Success", JOptionPane.INFORMATION_MESSAGE);
                //                resetField();
            } else {
                System.out.println("Register aborted.");
                JOptionPane.showMessageDialog(this, "Register aborted.", "Cancel Register", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error occurred while registering.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnRegisterActionPerformed

    private void jtfField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfField1ActionPerformed

    private void jBtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRefreshActionPerformed
        // TODO add your handling code here:
        String refreshQuery = "SELECT * FROM " + section;
        connectQuery(refreshQuery);
        //        populateTable(jTable, jspTable);
    }//GEN-LAST:event_jBtnRefreshActionPerformed

    private boolean checkEmpty() {
        for (int i = 0; i < fieldCount; i++) {
            String textFieldAccessor = "jtfField" + Integer.toString(i+1);
            if (jtfMap.get(textFieldAccessor).getText().trim().isEmpty()) {
                return true;
            }
        }
        return false;
    }
    private void connectQuery(String sqlQuery){
        try {
            connection = DriverManager.getConnection(connectionUrl);
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sqlQuery);
        } catch (SQLException e){
            e.printStackTrace();
        }
    }
    
    private String[] extractData(JTable table, int row, int col){
        int colCount = table.getColumnCount();
        String[] extracted = new String[colCount-1]; // -1 to exclude button
        try {
            for (int i = 0; i<colCount-1; i++){
            extracted[i] = table.getValueAt(row, i).toString();
            System.out.println(extracted[i]);
        }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return extracted;
    }  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardPayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardPayment().setVisible(false);
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnRefresh;
    private javax.swing.JButton jBtnRegister;
    private javax.swing.JTable jTable;
    private javax.swing.JButton jbtnBackMenu;
    private javax.swing.JLabel jlField1;
    private javax.swing.JLabel jlField10;
    private javax.swing.JLabel jlField11;
    private javax.swing.JLabel jlField12;
    private javax.swing.JLabel jlField13;
    private javax.swing.JLabel jlField2;
    private javax.swing.JLabel jlField3;
    private javax.swing.JLabel jlField4;
    private javax.swing.JLabel jlField5;
    private javax.swing.JLabel jlField6;
    private javax.swing.JLabel jlField7;
    private javax.swing.JLabel jlField8;
    private javax.swing.JLabel jlField9;
    private javax.swing.JLabel jlSectionDetail;
    private javax.swing.JLabel jlSectionTitle;
    private javax.swing.JLabel jlSectionTitle1;
    private javax.swing.JLabel jlSidebarTitle;
    private javax.swing.JLabel jlSidebarTitle1;
    private javax.swing.JLabel jlSidebarTitle3;
    private javax.swing.JLabel jlSidebarTitle4;
    private javax.swing.JLabel jlSidebarTitle5;
    private javax.swing.JPanel jpContent;
    private javax.swing.JPanel jpContent2;
    private javax.swing.JPanel jpDetail;
    private javax.swing.JPanel jpSidebar;
    private javax.swing.JScrollPane jspDetail;
    private javax.swing.JScrollPane jspTable;
    private javax.swing.JTextField jtfField1;
    private javax.swing.JTextField jtfField10;
    private javax.swing.JTextField jtfField11;
    private javax.swing.JTextField jtfField12;
    private javax.swing.JTextField jtfField13;
    private javax.swing.JTextField jtfField2;
    private javax.swing.JTextField jtfField3;
    private javax.swing.JTextField jtfField4;
    private javax.swing.JTextField jtfField5;
    private javax.swing.JTextField jtfField6;
    private javax.swing.JTextField jtfField7;
    private javax.swing.JTextField jtfField8;
    private javax.swing.JTextField jtfField9;
    // End of variables declaration//GEN-END:variables
}
