/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package horizonlogistic;

import java.sql.*;
import java.util.Arrays;
import java.util.Scanner;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAYHAN EGAR
 */
public class DashboardAdmin extends javax.swing.JFrame {
    
    String connectionUrl = "jdbc:sqlserver://HASHBROWN:1433;"
                + "database=Horizon_Logistic;"
                + "user=sa;"
                + "password=basisdata;"
                + "encrypt=false;"
                + "trustServerCertificate=false;"
                + "loginTimeout=30;";
    
    ResultSet resultSet = null;
    Connection connection;
    Statement statement;
    PreparedStatement preparedStatement;
    
    /**
     * Creates new form DashboardAdmin
     */
    public DashboardAdmin() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpSidebar = new javax.swing.JPanel();
        jlSidebarTitle = new javax.swing.JLabel();
        jBtnCustomer = new javax.swing.JButton();
        jBtnShipment = new javax.swing.JButton();
        jBtnEmployee = new javax.swing.JButton();
        jBtnClearance = new javax.swing.JButton();
        jBtnKendaraan = new javax.swing.JButton();
        jBtnDeliveryLeg = new javax.swing.JButton();
        jBtnDroppoint = new javax.swing.JButton();
        jBtnPayment = new javax.swing.JButton();
        jBtnOperation = new javax.swing.JButton();
        jBtnLogout = new javax.swing.JButton();
        jpContent = new javax.swing.JPanel();
        jlSectionTitle = new javax.swing.JLabel();
        jtfKeywords = new javax.swing.JTextField();
        jBtnSearch = new javax.swing.JButton();
        jspTable = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jlSectionDetail = new javax.swing.JLabel();
        jBtnRefresh = new javax.swing.JButton();
        jspDetail = new javax.swing.JScrollPane();
        jpDetail = new javax.swing.JPanel();
        jtfField1 = new javax.swing.JTextField();
        jlField1 = new javax.swing.JLabel();
        jlField2 = new javax.swing.JLabel();
        jtfField2 = new javax.swing.JTextField();
        jtfField3 = new javax.swing.JTextField();
        jlField3 = new javax.swing.JLabel();
        jlField4 = new javax.swing.JLabel();
        jlField5 = new javax.swing.JLabel();
        jtfField4 = new javax.swing.JTextField();
        jtfField5 = new javax.swing.JTextField();
        jtfField6 = new javax.swing.JTextField();
        jtfField7 = new javax.swing.JTextField();
        jtfField8 = new javax.swing.JTextField();
        jtfField9 = new javax.swing.JTextField();
        jtfField10 = new javax.swing.JTextField();
        jtfField11 = new javax.swing.JTextField();
        jtfField12 = new javax.swing.JTextField();
        jtfField13 = new javax.swing.JTextField();
        jlField6 = new javax.swing.JLabel();
        jlField7 = new javax.swing.JLabel();
        jlField8 = new javax.swing.JLabel();
        jlField9 = new javax.swing.JLabel();
        jlField10 = new javax.swing.JLabel();
        jlField11 = new javax.swing.JLabel();
        jlField12 = new javax.swing.JLabel();
        jlField13 = new javax.swing.JLabel();
        jbEdit = new javax.swing.JButton();
        jBtnSave = new javax.swing.JButton();
        jBtnAdd = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Horizon Logistic");
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);

        jpSidebar.setBackground(new java.awt.Color(255, 255, 255));
        jpSidebar.setFocusable(false);
        jpSidebar.setPreferredSize(new java.awt.Dimension(250, 600));

        jlSidebarTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlSidebarTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSidebarTitle.setText("Horizon Logistic");

        jBtnCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnCustomer.setText("Customer");
        jBtnCustomer.setPreferredSize(new java.awt.Dimension(150, 30));
        jBtnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCustomerActionPerformed(evt);
            }
        });

        jBtnShipment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnShipment.setText("Shipment");
        jBtnShipment.setPreferredSize(new java.awt.Dimension(150, 30));
        jBtnShipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnShipmentActionPerformed(evt);
            }
        });

        jBtnEmployee.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnEmployee.setText("Employee");
        jBtnEmployee.setPreferredSize(new java.awt.Dimension(150, 30));
        jBtnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEmployeeActionPerformed(evt);
            }
        });

        jBtnClearance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnClearance.setText("Clearance");
        jBtnClearance.setPreferredSize(new java.awt.Dimension(150, 30));
        jBtnClearance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearanceActionPerformed(evt);
            }
        });

        jBtnKendaraan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnKendaraan.setText("Kendaraan");
        jBtnKendaraan.setPreferredSize(new java.awt.Dimension(150, 30));
        jBtnKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKendaraanActionPerformed(evt);
            }
        });

        jBtnDeliveryLeg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnDeliveryLeg.setText("Delivery Leg");
        jBtnDeliveryLeg.setPreferredSize(new java.awt.Dimension(150, 30));
        jBtnDeliveryLeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeliveryLegActionPerformed(evt);
            }
        });

        jBtnDroppoint.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnDroppoint.setText("Drop Point");
        jBtnDroppoint.setPreferredSize(new java.awt.Dimension(150, 30));
        jBtnDroppoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDroppointActionPerformed(evt);
            }
        });

        jBtnPayment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnPayment.setText("Payment");
        jBtnPayment.setPreferredSize(new java.awt.Dimension(150, 30));
        jBtnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPaymentActionPerformed(evt);
            }
        });

        jBtnOperation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnOperation.setText("Operation");
        jBtnOperation.setPreferredSize(new java.awt.Dimension(150, 30));
        jBtnOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOperationActionPerformed(evt);
            }
        });

        jBtnLogout.setBackground(new java.awt.Color(255, 0, 0));
        jBtnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnLogout.setForeground(new java.awt.Color(255, 255, 255));
        jBtnLogout.setText("Log out");
        jBtnLogout.setPreferredSize(new java.awt.Dimension(150, 30));

        javax.swing.GroupLayout jpSidebarLayout = new javax.swing.GroupLayout(jpSidebar);
        jpSidebar.setLayout(jpSidebarLayout);
        jpSidebarLayout.setHorizontalGroup(
            jpSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlSidebarTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jpSidebarLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jpSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnShipment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnClearance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDeliveryLeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDroppoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jpSidebarLayout.setVerticalGroup(
            jpSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSidebarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlSidebarTitle)
                .addGap(18, 18, 18)
                .addComponent(jBtnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnShipment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnClearance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnDeliveryLeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnDroppoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jpContent.setBackground(new java.awt.Color(255, 255, 255));
        jpContent.setPreferredSize(new java.awt.Dimension(600, 100));

        jlSectionTitle.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jlSectionTitle.setText("-Relation-");
        jlSectionTitle.setPreferredSize(new java.awt.Dimension(100, 32));

        jtfKeywords.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfKeywords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfKeywordsActionPerformed(evt);
            }
        });

        jBtnSearch.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnSearch.setText("Search");
        jBtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearchActionPerformed(evt);
            }
        });

        jspTable.setBackground(new java.awt.Color(255, 255, 255));
        jspTable.setPreferredSize(new java.awt.Dimension(690, 240));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspTable.setViewportView(jTable);

        jlSectionDetail.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jlSectionDetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSectionDetail.setText("-Detail-");
        jlSectionDetail.setPreferredSize(new java.awt.Dimension(100, 32));

        jBtnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnRefresh.setText("Refresh");

        jpDetail.setBackground(new java.awt.Color(255, 255, 255));
        jpDetail.setPreferredSize(new java.awt.Dimension(450, 500));

        jlField1.setText("field-1");

        jlField2.setText("field-2");

        jlField3.setText("field-3");

        jlField4.setText("field-4");

        jlField5.setText("field-5");

        jlField6.setText("field-6");

        jlField7.setText("field-7");

        jlField8.setText("field-8");

        jlField9.setText("field-9");

        jlField10.setText("field-10");

        jlField11.setText("field-11");

        jlField12.setText("field-12");

        jlField13.setText("field-13");

        javax.swing.GroupLayout jpDetailLayout = new javax.swing.GroupLayout(jpDetail);
        jpDetail.setLayout(jpDetailLayout);
        jpDetailLayout.setHorizontalGroup(
            jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetailLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDetailLayout.createSequentialGroup()
                        .addComponent(jlField1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfField1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDetailLayout.createSequentialGroup()
                        .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlField2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlField3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlField4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlField5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlField6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlField7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlField8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlField9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlField10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlField11, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlField12, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlField13, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfField2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfField3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfField4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfField5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfField6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfField7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfField8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfField9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfField10, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfField11, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfField12, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfField13, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jpDetailLayout.setVerticalGroup(
            jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDetailLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlField2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlField3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlField4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlField5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlField6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlField7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlField8)
                    .addComponent(jtfField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlField9)
                    .addComponent(jtfField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlField10)
                    .addComponent(jtfField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlField11)
                    .addComponent(jtfField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlField12)
                    .addComponent(jtfField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlField13)
                    .addComponent(jtfField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jspDetail.setViewportView(jpDetail);

        jbEdit.setText("Edit");

        jBtnSave.setText("Save");

        jBtnAdd.setText("New");

        jBtnDelete.setText("Delete");

        javax.swing.GroupLayout jpContentLayout = new javax.swing.GroupLayout(jpContent);
        jpContent.setLayout(jpContentLayout);
        jpContentLayout.setHorizontalGroup(
            jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContentLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jspTable, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jpContentLayout.createSequentialGroup()
                            .addComponent(jlSectionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfKeywords, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBtnSearch)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBtnRefresh)))
                    .addComponent(jlSectionDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpContentLayout.createSequentialGroup()
                        .addComponent(jspDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnDelete))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jpContentLayout.setVerticalGroup(
            jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContentLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfKeywords)
                    .addComponent(jBtnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlSectionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jspTable, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlSectionDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jspDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpContentLayout.createSequentialGroup()
                        .addComponent(jbEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnAdd)))
                .addGap(102, 102, 102))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jpContent, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCustomerActionPerformed
        // TODO add your handling code here:
        String sqlQuery = "SELECT * FROM customer";
        jlSectionTitle.setText("Customer");
        jlSectionDetail.setText("Customer Detail");
        connectQuery(sqlQuery);
        populateTable(jTable, jspTable);
    }//GEN-LAST:event_jBtnCustomerActionPerformed

    private void jtfKeywordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfKeywordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfKeywordsActionPerformed

    private void jBtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSearchActionPerformed

    private void jBtnKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKendaraanActionPerformed
        // TODO add your handling code here:
        String sqlQuery = "SELECT * FROM kendaraan";
        jlSectionTitle.setText("Kendaraan");
        jlSectionDetail.setText("Kendaraan Detail");
        connectQuery(sqlQuery);
        populateTable(jTable, jspTable);
    }//GEN-LAST:event_jBtnKendaraanActionPerformed

    private void jBtnShipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnShipmentActionPerformed
        // TODO add your handling code here:
        String sqlQuery = "SELECT * FROM shipment";
        jlSectionTitle.setText("Shipment");
        jlSectionDetail.setText("Shipment Detail");
        connectQuery(sqlQuery);
        populateTable(jTable, jspTable);
    }//GEN-LAST:event_jBtnShipmentActionPerformed

    private void jBtnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEmployeeActionPerformed
        // TODO add your handling code here:
        String sqlQuery = "SELECT * FROM employee";
        jlSectionTitle.setText("Employee");
        jlSectionDetail.setText("Employee Detail");
        connectQuery(sqlQuery);
        populateTable(jTable, jspTable);
    }//GEN-LAST:event_jBtnEmployeeActionPerformed

    private void jBtnClearanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearanceActionPerformed
        // TODO add your handling code here:
        String sqlQuery = "SELECT * FROM clearance";
        jlSectionTitle.setText("Clearance");
        jlSectionDetail.setText("Clearance Detail");
        connectQuery(sqlQuery);
        populateTable(jTable, jspTable);
    }//GEN-LAST:event_jBtnClearanceActionPerformed

    private void jBtnDeliveryLegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeliveryLegActionPerformed
        // TODO add your handling code here:
        String sqlQuery = "SELECT * FROM delivery_leg";
        jlSectionTitle.setText("Delivery Leg");
        jlSectionDetail.setText("Deliv. Leg Detail");
        connectQuery(sqlQuery);
        populateTable(jTable, jspTable);
    }//GEN-LAST:event_jBtnDeliveryLegActionPerformed

    private void jBtnDroppointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDroppointActionPerformed
        // TODO add your handling code here:
        String sqlQuery = "SELECT * FROM droppoint";
        jlSectionTitle.setText("Drop point");
        jlSectionDetail.setText("Drop point Detail");
        connectQuery(sqlQuery);
        populateTable(jTable, jspTable);
    }//GEN-LAST:event_jBtnDroppointActionPerformed

    private void jBtnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPaymentActionPerformed
        // TODO add your handling code here:
        String sqlQuery = "SELECT * FROM payment";
        jlSectionTitle.setText("Payment");
        jlSectionDetail.setText("Payment Detail");
        connectQuery(sqlQuery);
        populateTable(jTable, jspTable);
    }//GEN-LAST:event_jBtnPaymentActionPerformed

    private void jBtnOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOperationActionPerformed
        // TODO add your handling code here:
        String sqlQuery = "SELECT * FROM operates";
        jlSectionTitle.setText("Operation");
        jlSectionDetail.setText("Operation Detail");
        connectQuery(sqlQuery);
        populateTable(jTable, jspTable);
    }//GEN-LAST:event_jBtnOperationActionPerformed

    
    private void connectQuery(String sqlQuery){
        try {
            connection = DriverManager.getConnection(connectionUrl);
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sqlQuery);
        } catch (SQLException e){
            e.printStackTrace();
        }
    }
    
    private void populateTable(JTable table, JScrollPane scrollPane){
        
        DefaultTableModel tableModel = new DefaultTableModel();
        try {
            
            int rowCount = resultSet.getRow();
            int colCount = resultSet.getMetaData().getColumnCount();
            
            // Add columns to the tableModel
            for(int i = 1; i<= colCount; i++) {
                tableModel.addColumn(resultSet.getMetaData().getColumnName(i));
            }
            
            // Add detail button column
            tableModel.addColumn("Detail");
            
            // Print data
            while (resultSet.next()){
                Object[] rowData = new Object[colCount + 1]; // +1 To add column button
                for (int i = 1; i <= colCount; i++) {
                    rowData[i - 1] = resultSet.getObject(i);
                }
                // Add button placeholder in the "Detail" column
                rowData[colCount] = "Button";
                tableModel.addRow(rowData);
            }
            
            table.setModel(tableModel);
            table.getColumnModel().getColumn(colCount).setCellRenderer(new ButtonRenderer());
            scrollPane.setViewportView(table);
            table.setPreferredScrollableViewportSize(table.getPreferredSize());
            
            table.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    int col = table.columnAtPoint(evt.getPoint());
                    int row = table.rowAtPoint(evt.getPoint());
                    
                    if (col == colCount) {
                        System.out.println("Button clicked on row " + row);
                        
                        // TODO add extractRowData() function here
                        
                        // TODO perform actions with the extracted data here
                        
                        // Set editable false
                        
                        
                    }
                }
            });
            
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnClearance;
    private javax.swing.JButton jBtnCustomer;
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnDeliveryLeg;
    private javax.swing.JButton jBtnDroppoint;
    private javax.swing.JButton jBtnEmployee;
    private javax.swing.JButton jBtnKendaraan;
    private javax.swing.JButton jBtnLogout;
    private javax.swing.JButton jBtnOperation;
    private javax.swing.JButton jBtnPayment;
    private javax.swing.JButton jBtnRefresh;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JButton jBtnSearch;
    private javax.swing.JButton jBtnShipment;
    private javax.swing.JTable jTable;
    private javax.swing.JButton jbEdit;
    private javax.swing.JLabel jlField1;
    private javax.swing.JLabel jlField10;
    private javax.swing.JLabel jlField11;
    private javax.swing.JLabel jlField12;
    private javax.swing.JLabel jlField13;
    private javax.swing.JLabel jlField2;
    private javax.swing.JLabel jlField3;
    private javax.swing.JLabel jlField4;
    private javax.swing.JLabel jlField5;
    private javax.swing.JLabel jlField6;
    private javax.swing.JLabel jlField7;
    private javax.swing.JLabel jlField8;
    private javax.swing.JLabel jlField9;
    private javax.swing.JLabel jlSectionDetail;
    private javax.swing.JLabel jlSectionTitle;
    private javax.swing.JLabel jlSidebarTitle;
    private javax.swing.JPanel jpContent;
    private javax.swing.JPanel jpDetail;
    private javax.swing.JPanel jpSidebar;
    private javax.swing.JScrollPane jspDetail;
    private javax.swing.JScrollPane jspTable;
    private javax.swing.JTextField jtfField1;
    private javax.swing.JTextField jtfField10;
    private javax.swing.JTextField jtfField11;
    private javax.swing.JTextField jtfField12;
    private javax.swing.JTextField jtfField13;
    private javax.swing.JTextField jtfField2;
    private javax.swing.JTextField jtfField3;
    private javax.swing.JTextField jtfField4;
    private javax.swing.JTextField jtfField5;
    private javax.swing.JTextField jtfField6;
    private javax.swing.JTextField jtfField7;
    private javax.swing.JTextField jtfField8;
    private javax.swing.JTextField jtfField9;
    private javax.swing.JTextField jtfKeywords;
    // End of variables declaration//GEN-END:variables
}
